#services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=spring_ai'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - '3306:3306'
##  ollama:
##    image: 'ollama/ollama:latest'
##    ports:
##      - '11434:11434'
##  redis:
##    image: 'redis:latest'
##    ports:
##      - '6379:6379'
#
#
#
